### ISSUE TITLE
Posting code?

### ISSUE THREAD

**Issue by darrenstrash** [avdgrinten/vc-satreduce#1]
Hello! I am very excited to experiment with the code from your ALENEX paper "SAT-and-Reduce for Vertex Cover: Accelerating Branch-and-Reduce". Will you be posting it soon?

**Comment by avdgrinten** [comment]
Sorry, I have been busy for quite some time but the code is now pushed.

Building the code might still be a bit annoying due to the external dependency on the CaDiCaL SAT solver; once I have the time, I will try to add a Docker image to automate the process.

**Comment by darrenstrash** [comment]
Thank you!

**Comment by schulzchristian** [comment]
Thx Alexander :) the link to the sat solver is currently not working. (And i believe a licence file is missing atm).

Thanks for providing the code here.

Best
Christian

**Comment by avdgrinten** [comment]
Hi Christian,

indeed, I messed up the markdown syntax. Both issues should be fixed now :)

Best,
Alexander
